version: 2
updates:
  # Check for npm updates at the root of the repository
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "201Harsh"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
